### PR TITLE
Devhub 949/cypress rt

### PR DESCRIPTION
**Pull request by harikakotipalli**
Adding cypress support

### CODE REVIEW

**Review by mcolella14 — APPROVED** [review]
Looks great! Pulled down and tested locally and everything is running smoothly. However, the ticket also included adding [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) to the project. We don't have any custom components at the moment though, so there's really nothing to test yet with React Testing Library. 

Just wondering if we should hold off until we have custom components to add React Testing Library, or add and configure it in this PR. @gfunk1230 what are your thoughts? 

Regardless, everything looks good here!

**Comment by harikakotipalli** [comment]
Working on adding React testing library.

**Comment by harikakotipalli** [comment]
Added React testing library setup.

**Comment by mcolella14** [comment]
LGTM!

**Comment by gfunk1230** [comment]
> Looks great! Pulled down and tested locally and everything is running smoothly. However, the ticket also included adding [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) to the project. We don't have any custom components at the moment though, so there's really nothing to test yet with React Testing Library.
> 
> Just wondering if we should hold off until we have custom components to add React Testing Library, or add and configure it in this PR. @gfunk1230 what are your thoughts?
> 
> Regardless, everything looks good here!

@mcolella14 sorry late to respond here but if we can get React testing library wired up that would be great.

**Comment by gfunk1230** [comment]
@harikakotipalli Looks great!

**Review by gfunk1230 — APPROVED** [review]

**Pull request merged**
